global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'secure-health-backend'
    static_configs:
      - targets: ['secure-health-api:8080']  # use the alias, NOT secure_health_api
    metrics_path: /actuator/prometheus